### PR TITLE
11.0 on Raspberry

### PR DESCRIPTION
**Pull request by luca-vercelli**
This script has been used to install Odoo 11.0 on Raspberry Pi 4, with Raspbian 10 as OS.

### CODE REVIEW

**Comment by Yenthe666** [comment]
Hmm interesting. Is there a reason why you'd want to install a full Odoo instance on a Raspberry though?

**Comment by luca-vercelli** [comment]
Hi,

yes, I think this is a good solution for my use case. It's a very very 
small agency, with 2 users, low budget, no fixed laptops / PC's in their 
office, and moreover they want to access Odoo from outside the network.

Raspberry Pi can stand up for years consuming few energy.


Il 07/01/2020 14:22, Yenthe Van Ginneken ha scritto:

**Comment by Yenthe666** [comment]
Could you tell me on which Raspberry Pi version it runs with how much RAM/storage? You have no issues whatsoever?

**Comment by luca-vercelli** [comment]
I am using Raspberry Pi 4 with 4GB RAM and 32GB microSD.

The access to Odoo from browser is a little bit slow, but after that it 
works quite good.



Il 07/01/2020 15:00, Yenthe Van Ginneken ha scritto:

**Comment by Yenthe666** [comment]
I've decided to add it in for those who'd like to use it :) Thank you very much @luca-vercelli! 🎈

**Pull request merged**
