### PR TITLE
9.0

### PR DESCRIPTION
**Pull request by cakbulut**
Hi,

I want install odor 9 on ubuntu 18_04. I am using your script but the server do not start. Have you got experience with this.

Would be great if you could help me. On ubuntu 16_04 your script worked great.

Best regards
Cetin

### CODE REVIEW

**Comment by jiad** [comment]
> Hi,
> 
> I want install odor 9 on ubuntu 18_04. I am using your script but the server do not start. Have you got experience with this.
> 
> Would be great if you could help me. On ubuntu 16_04 your script worked great.
> 
> Best regards
> Cetin

Yes. agree with you. same problem. odoo 9 doesn't run at all. no matter using "sudo service odoo-server restart", still no working.

Anybody can fix? Thanks in advance.

**Comment by Yenthe666** [comment]
Please run it from the terminal (`./odoo-bin -c /etc/your-odoo-server.conf`) and then give me the output from your logfile.

**Comment by jiad** [comment]
> Please run it from the terminal (`./odoo-bin -c /etc/your-odoo-server.conf`) and then give me the output from your logfile.

sorry, not available. reinstalling ubuntu now.

I found the depency named python-pybabel and pypdf not available in ubuntu18.04,   they are renamed as python-babel and python-pypdf2.

**Comment by cakbulut** [comment]
> Please run it from the terminal (`./odoo-bin -c /etc/your-odoo-server.conf`) and then give me the output from your logfile.

As Jiad said it is not available. There are a lot of python components missing. I have manually installed odoo9 on ubuntu 18_04 and that worked. But of course you script would be more convenient. The only issue which I have with the manual setup is that odoo is not available as a service.

**Comment by Yenthe666** [comment]
@cakbulut why wouldn't it be available? If you run Odoo from the terminal and connect to the IP then the log will be generated and I need a stacktrace to see what is missing.

**Comment by cakbulut** [comment]
> @cakbulut why wouldn't it be available? If you run Odoo from the terminal and connect to the IP then the log will be generated and I need a stacktrace to see what is missing.

Have installed a new VM with ubuntu 18. Now I will execute your script. Will give you the result in a few minutes.

**Comment by cakbulut** [comment]
Hi,

I tried to execute the command python odoo.py in folder /odoo/odoo-server

The result is:

Traceback (most recent call last):
  File "odoo.py", line 160, in <module>
    main()
  File "odoo.py", line 156, in main
    import openerp
  File "/odoo/odoo-server/openerp/__init__.py", line 64, in <module>
    import modules
  File "/odoo/odoo-server/openerp/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/odoo/odoo-server/openerp/modules/graph.py", line 13, in <module>
    import openerp.osv as osv
  File "/odoo/odoo-server/openerp/osv/__init__.py", line 4, in <module>
    import osv
  File "/odoo/odoo-server/openerp/osv/osv.py", line 4, in <module>
    from ..exceptions import except_orm
  File "/odoo/odoo-server/openerp/exceptions.py", line 16, in <module>
    from tools.func import frame_codeinfo
  File "/odoo/odoo-server/openerp/tools/__init__.py", line 8, in <module>
    from misc import *
  File "/odoo/odoo-server/openerp/tools/misc.py", line 16, in <module>
    import passlib.utils
ImportError: No module named passlib.utils

**Comment by cakbulut** [comment]
Hi,

I have installed all the modules, which odoo reported in the error messages. Now the is system is successfully installed. I have used this list

 sudo apt-get install python-dateutils / python-docutils / python-feedparser / python-gevent / python-lxml / python-gdata / python-ldap / python-mock python-mako / python-psutil / python-psycopg2 / python-unittest2   /  python-libxslt1 /  python-pybabel / python-pychart / python-openid / python-pydot /  python-tz /  python-pyparsing /   python-reportlab/  python-simplejson / python-vatnumber / python-vobject / python-webdav / python-werkzeug / python-yaml / python-xlwt / python-zsi
(Source: https://www.odoo.com/de_DE/forum/hilfe-1/question/importerror-no-module-named-decorator-63302)

But it was not sufficient. Tomorrow I will send a list of all modules which are necessary.

Have a good night.

Best regards

**Comment by Yenthe666** [comment]
Thanks a lot, looking forward to the whole list :) 
The ones such as LDAP are weird because they're listed:
https://github.com/Yenthe666/InstallScript/blob/06e4228a11159955983240d85638935e3e231a02/odoo_install.sh#L65

**Comment by cakbulut** [comment]
Hi,

sorry I am a little bit late but I have done several tests.
After executing your script following modules must be installed on Ubuntu 18 to get odoo run. You can see the error message and the executed command to install the missing module. Would be great if you could extend your script for odoo version 9.

ImportError: No module named passlib.utils
sudo apt-get install python-passlib

ImportError: No module named werkzeug.utils
sudo apt-get install python-werkzeug

ImportError: No module named decorator
sudo apt-get install python-decorator

ImportError: No module named dateutil.relativedelta
sudo pip install python-dateutil --upgrade

ImportError: No module named pytz
sudo pip install pytz

ImportError: No module named psycopg2
sudo apt-get install python-psycopg2

ImportError: No module named babel.messages
sudo pip install babel

ImportError: No module named yaml
sudo apt-get install python-yaml

ImportError: No module named PIL
sudo pip install Pillow

ImportError: No module named reportlab.platypus
sudo apt-get install python-reportlab

ImportError: No module named mako
sudo apt-get install python-mako

ImportError: No module named pychart
sudo apt-get install python-pychart

ImportError: No module named psutil
sudo apt-get install python-psutil 

ImportError: No module named requests
sudo pip install requests

ImportError: No module named jinja2
sudo pip install Jinja2

ImportError: No module named docutils
sudo pip install docutils

ImportError: No module named pyPdf
sudo pip install pyPdf

ImportError: No module named mock
sudo apt-get install python-mock

Pdf were not generated
sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

Best regards
cakbulut

**Comment by Yenthe666** [comment]
Hmm but quite some that you've listed are actually in there. See
https://github.com/Yenthe666/InstallScript/blob/06e4228a11159955983240d85638935e3e231a02/odoo_install.sh#L65

What is the output from the install script itself when it is ran?

**Comment by cakbulut** [comment]
The output are the echo messages in the end of the script, but the server is not started. If you start the server manually you receive the first message from the list.

**Comment by jiad** [comment]
> update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults

Found this error after install your script in ubuntu 18.04

**Pull request closed without merging**
