### PR TITLE
[UPD] Choose install Postgresql

### PR DESCRIPTION
**Pull request by altanmur**

### CODE REVIEW

**Comment by altanmur** [comment]
Use in AWS EC2

**Comment by Yenthe666** [comment]
Euh but why would you ever not want to install postgreSQL?

**Comment by altanmur** [comment]
> Euh but why would you ever not want to install postgreSQL?

Because Use The AWS RDS

**Comment by altanmur** [comment]
Maybe app server, db server separate server or VPS

**Comment by Yenthe666** [comment]
Honestly, I'm not sure if I'd want to add that also as an option. Our options list is already becoming pretty huge 😕

**Comment by sswapnesh** [comment]
:+1:

**Comment by Yenthe666** [comment]
I thought about this again but we already have so many options that I'd rather not add this.

**Pull request closed without merging**
